services:
  bot:
    image: anasxonunical/buildroid:v1.0.0
    ports:
      - "4000:4000" # host_port:container_port
      - "4040:4040" # host_port:container_port
    entrypoint: ./build/Buildroid
    container_name: buildroid_container